CREATE TABLE tb_usuario
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    criado_em TIMESTAMP(6) NOT NULL,
    nome      VARCHAR(120) NOT NULL,
    email     VARCHAR(150) NOT NULL,
    senha     VARCHAR(255) NOT NULL,

    PRIMARY KEY (id),

    CONSTRAINT uk_usuario_email UNIQUE (email)
);


CREATE TABLE tb_categoria
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    usuario_id INTEGER     NOT NULL,
    nome       VARCHAR(60) NOT NULL,

    PRIMARY KEY (id),

    CONSTRAINT uk_categoria_usuario_nome
        UNIQUE (usuario_id, nome),

    CONSTRAINT fk_categoria_usuario
        FOREIGN KEY (usuario_id)
            REFERENCES tb_usuario (id)
);


CREATE TABLE tb_produto
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome              VARCHAR(120)   NOT NULL,
    categoria_id      INTEGER        NOT NULL,
    usuario_id        INTEGER        NOT NULL,
    unidade           VARCHAR(3)     NOT NULL,
    quantidade_atual  NUMERIC(10, 3) NOT NULL,
    quantidade_minima NUMERIC(10, 3) NOT NULL,
    quantidade_ideal  NUMERIC(10, 3) NOT NULL,
    ativo             BOOLEAN        NOT NULL,
    criado_em         TIMESTAMP(6)   NOT NULL,
    atualizado_em     TIMESTAMP(6)   NOT NULL,
    data_validade     DATE,

    PRIMARY KEY (id),

    CONSTRAINT fk_produto_categoria
        FOREIGN KEY (categoria_id)
            REFERENCES tb_categoria (id),

    CONSTRAINT fk_produto_usuario
        FOREIGN KEY (usuario_id)
            REFERENCES tb_usuario (id),

    CONSTRAINT ck_produto_unidade
        CHECK (unidade IN ('UN', 'KG', 'G', 'L', 'ML', 'PCT'))
);


CREATE TABLE tb_lista_compra
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY,
    usuario_id    INTEGER      NOT NULL,
    criado_em     TIMESTAMP(6) NOT NULL,
    finalizado_em TIMESTAMP(6),
    status        VARCHAR(10)  NOT NULL,
    titulo        VARCHAR(120) NOT NULL,

    PRIMARY KEY (id),

    CONSTRAINT fk_lista_compra_usuario
        FOREIGN KEY (usuario_id)
            REFERENCES tb_usuario (id),

    CONSTRAINT ck_lista_compra_status
        CHECK (status IN ('ABERTA', 'FINALIZADA', 'CANCELADA'))
);


CREATE TABLE tb_lista_compra_item
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lista_id            INTEGER        NOT NULL,
    produto_id          INTEGER        NOT NULL,
    quantidade_sugerida NUMERIC(10, 3) NOT NULL,
    quantidade_comprada NUMERIC(10, 3),
    comprado            BOOLEAN        NOT NULL,

    PRIMARY KEY (id),

    CONSTRAINT uk_lista_produto
        UNIQUE (lista_id, produto_id),

    CONSTRAINT fk_item_lista
        FOREIGN KEY (lista_id)
            REFERENCES tb_lista_compra (id),

    CONSTRAINT fk_item_produto
        FOREIGN KEY (produto_id)
            REFERENCES tb_produto (id)
);


CREATE TABLE tb_movimentacao
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    produto_id INTEGER        NOT NULL,
    quantidade NUMERIC(10, 3) NOT NULL,
    criado_em  TIMESTAMP(6)   NOT NULL,
    tipo       VARCHAR(10)    NOT NULL,
    observacao VARCHAR(255),

    PRIMARY KEY (id),

    CONSTRAINT fk_movimentacao_produto
        FOREIGN KEY (produto_id)
            REFERENCES tb_produto (id),

    CONSTRAINT ck_movimentacao_tipo
        CHECK (tipo IN ('ENTRADA', 'SAIDA', 'AJUSTE', 'DESCARTE'))
);


CREATE INDEX idx_mov_produto_data
    ON tb_movimentacao (produto_id, criado_em);